# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 217f5a2482e017704882844d4dac202c5f268d93372b088a5641b45ef3a9dc214478072c591cc0d9af4aa5321720fccb4e908c865799accdd8fd55d50890b92b

test:
  secret_key_base: 3a9b8eb5fa84f9a81f1aeff3024401228f3440ad8570de6bc888c4eb59abed1d678392c01fa1eb04b4f8adf3aaa3cb55df83cd7876320ae19434deb3fdb801c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
